  # ------------------------------------------------------------------------------
  traefik-acme:
    image: traefik:${TRAEFIK_VER}
    command:
      --web --docker --docker.watch --docker.exposedbydefault=false --logLevel=DEBUG
      --acme --acme.acmelogging=true --acme.email=${TRAEFIK_ACME_EMAIL}
      --acme.onhostrule
      --acme.storage=/acme/certs.json --acme.entrypoint=https
      --defaultEntryPoints=${TRAEFIK_ENTRY_DEFAULT}
      --entryPoints='Name:http Address::${TRAEFIK_ENTRY_HTTP}'
      --entryPoints='Name:https Address::443 TLS'
    restart: always
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/null:/traefik.toml
      - ./var/data/acme:/acme
    networks:
      default:
        aliases:
          - traefik
