  # ------------------------------------------------------------------------------
  cis:
    image: nginx:1.13-alpine
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:${CIS_HOST}"
      - "traefik.port=80"
    depends_on:
      - webtail
      - webhook
      - traefik-fl
      - enfist
      - narra
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./apps/cis/html:/usr/share/nginx/html:ro
      - ./apps/cis/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./var/data/cis/hook.pub:/data/hook.pub:ro


  # ------------------------------------------------------------------------------
  webtail:
    image: lekovr/webtail:${CIS_WEBTAIL_VER}
    restart: always
    labels:
      - "traefik.enable=false"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./var/log:/var/log
    command: --root /var/log/webhook --log_level debug

  # ------------------------------------------------------------------------------
  webhook:
    image: dopos/webhook:${CIS_WEBHOOK_VER}
    restart: always
    labels:
      - "traefik.enable=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/cron.d:/etc/cron.d
      - ./var/data/cis/hook:/hook:ro
      - ./var:${DCAPE_ROOT}/var
    command: -hooks /etc/webhook/local.json -hooks /etc/webhook/remote.json -hotreload -nopanic -verbose
    environment:
      - DEPLOY_ROOT=${DCAPE_ROOT}/var
      - DEPLOY_PASS=${CIS_DEPLOY_PASS}
      - GIT_SSH_COMMAND=ssh -i /hook -o StrictHostKeyChecking=no

  # ------------------------------------------------------------------------------
  traefik-fl:
    image: dopos/traefik-fl:0.1
    restart: always
    labels:
      - "traefik.enable=false"

  # ------------------------------------------------------------------------------
  narra:
    image: dopos/narra:${CIS_NARRA_VER}
    restart: always
    labels:
      - "traefik.enable=false"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      --gitea_host ${CIS_GITEA_HOST} --cookie_sign ${CIS_SIGN_KEY} --cookie_crypt ${CIS_CRYPT_KEY} --gitea_org ${CIS_GITEA_ORG}
