  # ------------------------------------------------------------------------------
  portainer:
    image: portainer/portainer:${PORTAINER_VER}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:${PORTAINER_HOST}"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./var/data/portainer:/data
