  # ------------------------------------------------------------------------------
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VER}
    restart: always
    labels:
      - "dcape.traefik.tag=${DCAPE_TAG}"
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${DCAPE_HOST}`) && PathPrefix(`/port/`)"
      - "traefik.http.middlewares.portainer-prefix.stripprefix.prefixes=/port"
      - "traefik.http.routers.portainer.middlewares=portainer-prefix@docker"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./${DCAPE_VAR}/portainer:/data
