  # ------------------------------------------------------------------------------
  enfist:
    image: apisite/enfist:${ENFIST_VER}
    restart: always
    depends_on:
      db:
        condition: service_healthy
    command:
      /usr/bin/apisite --db.schema rpc --http_addr :8080
    labels:
      - "dcape.traefik.tag=${PROJECT_NAME}"
      - "traefik.enable=true"
      - "traefik.http.routers.enfist.rule=Host(`${CIS_HOST}`) && PathPrefix(`/conf/`)"
      - "traefik.http.middlewares.enfist-prefix.stripprefix.prefixes=/conf"
      - "traefik.http.routers.enfist.middlewares=narra,enfist-prefix@docker"
    environment:
      - PGHOST=db
      - PGDATABASE=${ENFIST_DB_TAG}
      - PGUSER=${ENFIST_DB_TAG}
      - PGPASSWORD=${ENFIST_DB_PASS}
      - PGSSLMODE=disable
      - GIN_MODE=release
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
