  # ------------------------------------------------------------------------------
  enfist:
    image: apisite/enfist:${ENFIST_VER}
    restart: always
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=false"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      /usr/bin/apisite --db_schema rpc --http_addr :8080
    environment:
      - PGHOST=db
      - PGDATABASE=${ENFIST_DB_TAG}
      - PGUSER=${ENFIST_DB_TAG}
      - PGPASSWORD=${ENFIST_DB_PASS}
      - PGSSLMODE=disable
      - GIN_MODE=release
